package Vista;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Interfaz_principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Interfaz_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botoniniciar = new javax.swing.JButton();
        botonregistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        textcorreo = new javax.swing.JTextField();
        textcntra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonarriba = new javax.swing.JButton();
        botonabajo = new javax.swing.JButton();
        foto3 = new javax.swing.JLabel();
        foto1 = new javax.swing.JLabel();
        foto4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botoncerrar = new javax.swing.JButton();
        botonminimizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(688, 399));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(null);

        jPanel1.setBackground(new Color(255,255,255));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/1)LOGIN.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 10, 70, 70);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        botoniniciar.setBackground(new java.awt.Color(255, 34, 44));
        botoniniciar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botoniniciar.setForeground(new java.awt.Color(255, 255, 255));
        botoniniciar.setText("LOGIN");
        botoniniciar.setBorder(null);
        botoniniciar.setBorderPainted(false);
        jPanel3.add(botoniniciar);
        botoniniciar.setBounds(190, 180, 70, 30);

        botonregistrar.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonregistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrar.setText("REGISTER");
        botonregistrar.setBorder(null);
        botonregistrar.setBorderPainted(false);
        jPanel3.add(botonregistrar);
        botonregistrar.setBounds(10, 180, 80, 30);

        jSeparator1.setBackground(new java.awt.Color(255, 34, 44));
        jSeparator1.setForeground(new java.awt.Color(255, 34, 44));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(60, 80, 200, 10);

        jLabel6.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel6.setText("CONTRASEÑA");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 90, 220, 20);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel7.setText("CORREO ELECTRÓNICO");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 10, 220, 20);

        jSeparator2.setBackground(new java.awt.Color(255, 34, 44));
        jSeparator2.setForeground(new java.awt.Color(255, 34, 44));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(60, 150, 200, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/2)candado.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 120, 34, 32);

        textcorreo.setBorder(null);
        jPanel3.add(textcorreo);
        textcorreo.setBounds(60, 50, 190, 30);

        textcntra.setBorder(null);
        textcntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcntraActionPerformed(evt);
            }
        });
        jPanel3.add(textcntra);
        textcntra.setBounds(60, 120, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/3)arroba.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 40, 40, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 80, 270, 220);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(340, 60, 300, 300);

        jPanel5.setBackground(new Color(255,255,255,50));
        jPanel5.setLayout(null);

        botonarriba.setBackground(new java.awt.Color(255, 255, 255));
        botonarriba.setForeground(new java.awt.Color(255, 255, 255));
        botonarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/4)arriba.png"))); // NOI18N
        botonarriba.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonarriba.setContentAreaFilled(false);
        botonarriba.setFocusPainted(false);
        botonarriba.setFocusable(false);
        botonarriba.setRequestFocusEnabled(false);
        jPanel5.add(botonarriba);
        botonarriba.setBounds(50, 0, 230, 60);

        botonabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/5)abajo.png"))); // NOI18N
        botonabajo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonabajo.setContentAreaFilled(false);
        jPanel5.add(botonabajo);
        botonabajo.setBounds(50, 330, 230, 40);

        foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/gato_desplazamiento2.png"))); // NOI18N
        jPanel5.add(foto3);
        foto3.setBounds(50, 0, 230, 370);

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/perro_desplazamiento2.png"))); // NOI18N
        jPanel5.add(foto1);
        foto1.setBounds(50, 0, 230, 370);

        foto4.setBackground(new java.awt.Color(255, 255, 255));
        foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/fond_desplazamiento.jpg"))); // NOI18N
        jPanel5.add(foto4);
        foto4.setBounds(50, 0, 230, 370);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(20, 10, 390, 370);

        botoncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar.png"))); // NOI18N
        botoncerrar.setBorderPainted(false);
        botoncerrar.setContentAreaFilled(false);
        botoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerrarActionPerformed(evt);
            }
        });

        botonminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/minimizar.png"))); // NOI18N
        botonminimizar.setBorderPainted(false);
        botonminimizar.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(590, 10, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/FONDO_R.USUARIO.jpeg"))); // NOI18N
        jLabel3.setFocusable(false);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 440);

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(4, 0, 690, 30);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcntraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcntraActionPerformed

    private void botoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoncerrarActionPerformed

    public JButton getBotonabajo() {
        return botonabajo;
    }

    public JLabel getFoto3() {
        return foto3;
    }

    public void setFoto3(JLabel foto3) {
        this.foto3 = foto3;
    }

    public JPasswordField getTextcntra() {
        return textcntra;
    }

    public void setTextcntra(JPasswordField textcntra) {
        this.textcntra = textcntra;
    }

    public void setBotonabajo(JButton botonabajo) {
        this.botonabajo = botonabajo;
    }

    public JButton getBotonarriba() {
        return botonarriba;
    }

    public void setBotonarriba(JButton botonarriba) {
        this.botonarriba = botonarriba;
    }

    
    public JButton getBotoncerrar() {
        return botoncerrar;
    }

    public void setBotoncerrar(JButton botoncerrar) {
        this.botoncerrar = botoncerrar;
    }

    public JButton getBotoniniciar() {
        return botoniniciar;
    }

    
    public void setBotoniniciar(JButton botoniniciar) {
        this.botoniniciar = botoniniciar;
    }

    public JButton getBotonminimizar() {
        return botonminimizar;
    }

    public void setBotonminimizar(JButton botonminimizar) {
        this.botonminimizar = botonminimizar;
    }

    public JButton getBotonregistrar() {
        return botonregistrar;
    }

    public void setBotonregistrar(JButton botonregistrar) {
        this.botonregistrar = botonregistrar;
    }

    public JLabel getFoto1() {
        return foto1;
    }

    public void setFoto1(JLabel foto1) {
        this.foto1 = foto1;
    }

    public JPasswordField getTextcerrar() {
        return textcntra;
    }

    public void setTextcerrar(JPasswordField textcerrar) {
        this.textcntra = textcerrar;
    }

    public JTextField getTextcorreo() {
        return textcorreo;
    }

    public void setTextcorreo(JTextField textcorreo) {
        this.textcorreo = textcorreo;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonabajo;
    private javax.swing.JButton botonarriba;
    private javax.swing.JButton botoncerrar;
    private javax.swing.JButton botoniniciar;
    private javax.swing.JButton botonminimizar;
    private javax.swing.JButton botonregistrar;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField textcntra;
    private javax.swing.JTextField textcorreo;
    // End of variables declaration//GEN-END:variables
}
