/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Registro_Adoptante extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Adoptante
     */
    public Registro_Adoptante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        button_cancelar_registro_usuario = new javax.swing.JButton();
        button_registro_usuario = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        cerrar_minif = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        text_Contraseña = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        contraseñasegundo = new javax.swing.JPasswordField();
        bajo = new javax.swing.JPanel();
        medio = new javax.swing.JPanel();
        alto = new javax.swing.JPanel();
        text_Usuario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Hombre = new javax.swing.JRadioButton();
        Mujer = new javax.swing.JRadioButton();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        calle_principal = new javax.swing.JTextField();
        calle_secundaria = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        numero_casa = new javax.swing.JSpinner();
        numero_mascotas = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(null);

        button_cancelar_registro_usuario.setBackground(new java.awt.Color(0, 0, 0));
        button_cancelar_registro_usuario.setForeground(new java.awt.Color(255, 255, 255));
        button_cancelar_registro_usuario.setText("Cancelar");
        button_cancelar_registro_usuario.setBorderPainted(false);
        jFrame1.getContentPane().add(button_cancelar_registro_usuario);
        button_cancelar_registro_usuario.setBounds(10, 280, 90, 30);

        button_registro_usuario.setBackground(new java.awt.Color(255, 34, 44));
        button_registro_usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button_registro_usuario.setForeground(new java.awt.Color(255, 255, 255));
        button_registro_usuario.setText("Registrar");
        button_registro_usuario.setBorderPainted(false);
        button_registro_usuario.setFocusPainted(false);
        button_registro_usuario.setFocusable(false);
        button_registro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registro_usuarioActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(button_registro_usuario);
        button_registro_usuario.setBounds(270, 280, 100, 30);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        cerrar_minif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar.png"))); // NOI18N
        cerrar_minif.setBorderPainted(false);
        cerrar_minif.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(cerrar_minif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(cerrar_minif)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jPanel9);
        jPanel9.setBounds(310, 0, 70, 40);

        jPanel6.setBackground(new Color(0,0,0,70));
        jPanel6.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/2)candado.png"))); // NOI18N
        jLabel19.setText("Contraseña:");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(10, 50, 114, 40);
        jPanel8.add(text_Contraseña);
        text_Contraseña.setBounds(150, 60, 160, 30);

        jLabel20.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Repetir Contraseña:");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(10, 120, 128, 30);
        jPanel8.add(contraseñasegundo);
        contraseñasegundo.setBounds(150, 120, 160, 30);

        bajo.setBackground(new java.awt.Color(0, 0, 0));
        bajo.setOpaque(false);

        javax.swing.GroupLayout bajoLayout = new javax.swing.GroupLayout(bajo);
        bajo.setLayout(bajoLayout);
        bajoLayout.setHorizontalGroup(
            bajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        bajoLayout.setVerticalGroup(
            bajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel8.add(bajo);
        bajo.setBounds(4, 100, 70, 10);

        medio.setOpaque(false);

        javax.swing.GroupLayout medioLayout = new javax.swing.GroupLayout(medio);
        medio.setLayout(medioLayout);
        medioLayout.setHorizontalGroup(
            medioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        medioLayout.setVerticalGroup(
            medioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel8.add(medio);
        medio.setBounds(78, 100, 90, 10);

        alto.setOpaque(false);

        javax.swing.GroupLayout altoLayout = new javax.swing.GroupLayout(alto);
        alto.setLayout(altoLayout);
        altoLayout.setHorizontalGroup(
            altoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        altoLayout.setVerticalGroup(
            altoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel8.add(alto);
        alto.setBounds(170, 100, 140, 10);

        text_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_UsuarioActionPerformed(evt);
            }
        });
        jPanel8.add(text_Usuario);
        text_Usuario.setBounds(120, 10, 190, 30);

        jLabel18.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/3)arroba.png"))); // NOI18N
        jLabel18.setText("Usuario:");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(10, 0, 88, 43);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(11, 43, 320, 160);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(226, 30, 56));
        jLabel21.setText("REGISTRAR CUENTA");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(91, 11, 163, 21);

        jFrame1.getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 50, 340, 220);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/FONDO_REGISTROUSUARIO.jpeg"))); // NOI18N
        jFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 380, 330);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(230, 20, 73, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(811, 554));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setLayout(null);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/minimizar.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        jPanel1.add(minimizar);
        minimizar.setBounds(720, 10, 50, 40);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        jPanel1.add(cerrar);
        cerrar.setBounds(760, 10, 50, 40);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(720, 10, 100, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel7.setText("Cedúla:");

        jLabel8.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel8.setText("Nombre:");

        jLabel9.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel9.setText("Apellido:");

        jLabel10.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de Nacimiento:");

        jLabel11.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel11.setText("Calle Principal:");

        jLabel12.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel12.setText("Género:");

        jLabel13.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel13.setText("Numero Casa:");

        buttonGroup1.add(Hombre);
        Hombre.setText("Hombre");

        buttonGroup1.add(Mujer);
        Mujer.setText("Mujer");
        Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel14.setText("Calle Secundaria:");

        jLabel15.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel15.setText("Número de Mascotas:");

        jLabel16.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel16.setText("Telefono");

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        numero_casa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        numero_mascotas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        Registrar.setBackground(new Color(255,34,44,50));
        Registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("Registrar");
        Registrar.setBorder(null);
        Registrar.setBorderPainted(false);

        cancelar.setBackground(new Color(43,94,255,50));
        cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.setBorder(null);
        cancelar.setBorderPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Hombre)
                                        .addGap(18, 18, 18)))
                                .addComponent(Mujer))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel11))
                                                .addGap(91, 91, 91))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(calle_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(calle_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(numero_mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calle_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calle_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mujer)
                            .addComponent(Hombre)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/LOGO_P2.jpeg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/LOGO_P1.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 60, 430, 470);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 2, 36)); // NOI18N
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 290, 170, 40);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 2, 36)); // NOI18N
        jLabel3.setText("REGISTRO DE ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 250, 290, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/WhatsApp Image 2021-04-02 at 19.09.44 (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 60, 350, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/FONDO_R.USUARIO.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 880, 590);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MujerActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarActionPerformed

    private void button_registro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registro_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_registro_usuarioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void text_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_UsuarioActionPerformed

    public JRadioButton getHombre() {
        return Hombre;
    }

    public void setHombre(JRadioButton Hombre) {
        this.Hombre = Hombre;
    }

    public JRadioButton getMujer() {
        return Mujer;
    }

    public void setMujer(JRadioButton Mujer) {
        this.Mujer = Mujer;
    }

    
    
    public JButton getButton_cancelar_registro_usuario() {
        return button_cancelar_registro_usuario;
    }

    public void setButton_cancelar_registro_usuario(JButton button_cancelar_registro_usuario) {
        this.button_cancelar_registro_usuario = button_cancelar_registro_usuario;
    }

    public JButton getButton_registro_usuario() {
        return button_registro_usuario;
    }

    public void setButton_registro_usuario(JButton button_registro_usuario) {
        this.button_registro_usuario = button_registro_usuario;
    }

    public JPasswordField getText_Contraseña() {
        return text_Contraseña;
    }

    public void setText_Contraseña(JPasswordField text_Contraseña) {
        this.text_Contraseña = text_Contraseña;
    }

    public JTextField getText_Usuario() {
        return text_Usuario;
    }

    public void setText_Usuario(JTextField text_Usuario) {
        this.text_Usuario = text_Usuario;
    }

    
    
    public JButton getRegistrar() {
        return Registrar;
    }

    public JFrame getjFrame1() {
        return jFrame1;
    }

    public void setjFrame1(JFrame jFrame1) {
        this.jFrame1 = jFrame1;
    }

    public void setRegistrar(JButton Registrar) {
        this.Registrar = Registrar;
    }

    public JTextField getApellido() {
        return apellido;
    }

    public void setApellido(JTextField apellido) {
        this.apellido = apellido;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JTextField getCalle_principal() {
        return calle_principal;
    }

    public void setCalle_principal(JTextField calle_principal) {
        this.calle_principal = calle_principal;
    }

    public JTextField getCalle_secundaria() {
        return calle_secundaria;
    }

    public void setCalle_secundaria(JTextField calle_secundaria) {
        this.calle_secundaria = calle_secundaria;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public JButton getCerrar_minif() {
        return cerrar_minif;
    }

    public void setCerrar_minif(JButton cerrar_minif) {
        this.cerrar_minif = cerrar_minif;
    }

    public JPanel getAlto() {
        return alto;
    }

    public void setAlto(JPanel alto) {
        this.alto = alto;
    }

    public JPanel getBajo() {
        return bajo;
    }

    public void setBajo(JPanel bajo) {
        this.bajo = bajo;
    }

    public JPasswordField getContraseñasegundo() {
        return contraseñasegundo;
    }

    public void setContraseñasegundo(JPasswordField contraseñasegundo) {
        this.contraseñasegundo = contraseñasegundo;
    }

    public JPanel getMedio() {
        return medio;
    }

    public void setMedio(JPanel medio) {
        this.medio = medio;
    }
 
    
    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    public JButton getCerrar() {
        return cerrar;
    }

    public void setCerrar(JButton cerrar) {
        this.cerrar = cerrar;
    }

    public JDateChooser getFecha_nacimiento() {
        return fecha_nacimiento;
    }

    public void setFecha_nacimiento(JDateChooser fecha_nacimiento) {
        this.fecha_nacimiento = fecha_nacimiento;
    }

    public JRadioButton getjRadioButton1() {
        return Hombre;
    }

    public void setjRadioButton1(JRadioButton jRadioButton1) {
        this.Hombre = jRadioButton1;
    }

    public JRadioButton getjRadioButton2() {
        return Mujer;
    }

    public void setjRadioButton2(JRadioButton jRadioButton2) {
        this.Mujer = jRadioButton2;
    }

    public JButton getMinimizar() {
        return minimizar;
    }

    public void setMinimizar(JButton minimizar) {
        this.minimizar = minimizar;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JSpinner getNumero_casa() {
        return numero_casa;
    }

    public void setNumero_casa(JSpinner numero_casa) {
        this.numero_casa = numero_casa;
    }

    public JSpinner getNumero_mascotas() {
        return numero_mascotas;
    }

    public void setNumero_mascotas(JSpinner numero_mascotas) {
        this.numero_mascotas = numero_mascotas;
    }

    public JTextField getTelefono() {
        return telefono;
    }

    public void setTelefono(JTextField telefono) {
        this.telefono = telefono;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Hombre;
    private javax.swing.JRadioButton Mujer;
    private javax.swing.JButton Registrar;
    private javax.swing.JPanel alto;
    private javax.swing.JTextField apellido;
    private javax.swing.JPanel bajo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_cancelar_registro_usuario;
    private javax.swing.JButton button_registro_usuario;
    private javax.swing.JTextField calle_principal;
    private javax.swing.JTextField calle_secundaria;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton cerrar_minif;
    private javax.swing.JPasswordField contraseñasegundo;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel medio;
    private javax.swing.JButton minimizar;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner numero_casa;
    private javax.swing.JSpinner numero_mascotas;
    private javax.swing.JTextField telefono;
    private javax.swing.JPasswordField text_Contraseña;
    private javax.swing.JTextField text_Usuario;
    // End of variables declaration//GEN-END:variables
}
